"use strict";

const {
  readRuntimeStaminaCurrent,
  readRuntimeStaminaMax,
  readRuntimeHpCurrent,
  readRuntimeHpMax,
  readRuntimeHungerCurrent,
  readRuntimeHungerMax,
  readRuntimeThirstCurrent,
  readRuntimeThirstMax,
  readRuntimeImmunityCurrent,
  readRuntimeImmunityMax,
  readRuntimeImmunityPercent,
  readRuntimeDiseaseLevel,
  readRuntimeDiseaseSeverity,
  readRuntimeSleepCurrent,
  readRuntimeSleepMax,
} = require("./runtimeVitals/readers");
const {
  syncRuntimeHp,
  syncRuntimeStamina,
  syncRuntimeHunger,
  syncRuntimeThirst,
  syncRuntimeImmunity,
  syncRuntimeDisease,
  syncRuntimeSleep,
} = require("./runtimeVitals/syncers");

module.exports = {
  readRuntimeStaminaCurrent,
  readRuntimeStaminaMax,
  readRuntimeHpCurrent,
  readRuntimeHpMax,
  readRuntimeHungerCurrent,
  readRuntimeHungerMax,
  readRuntimeThirstCurrent,
  readRuntimeThirstMax,
  readRuntimeImmunityCurrent,
  readRuntimeImmunityMax,
  readRuntimeImmunityPercent,
  readRuntimeDiseaseLevel,
  readRuntimeDiseaseSeverity,
  readRuntimeSleepCurrent,
  readRuntimeSleepMax,
  syncRuntimeHp,
  syncRuntimeStamina,
  syncRuntimeHunger,
  syncRuntimeThirst,
  syncRuntimeImmunity,
  syncRuntimeDisease,
  syncRuntimeSleep,
};
