"use strict";

const { DT_MAX } = require("../config");
const {
  MOVE_STAMINA_DRAIN_PER_SEC,
  MOVE_STAMINA_DRAIN_WARN_RATIO,
  MOVE_STAMINA_DRAIN_DANGER_RATIO,
  MOVE_STAMINA_DRAIN_WARN_MULTIPLIER,
  MOVE_STAMINA_DRAIN_DANGER_MULTIPLIER,
  STAMINA_BASE_REGEN_PER_SEC,
  HP_BASE_REGEN_PER_SEC,
  MOVE_SPEED_AT_ZERO_STAMINA_MULTIPLIER,
} = require("../../../config/movementConstants");

const DEFAULT_TERRAIN_DRAIN_MULTIPLIER = 1.0;
const DEFAULT_STAMINA_REGEN_MULTIPLIER = 1.0;
const DEFAULT_HP_REGEN_MULTIPLIER = 1.0;
const DEFAULT_HUNGER_ITEM_RECOVERY = 0;
const HUNGER_TICK_INTERVAL_MS = 60 * 1000;
// Uma barra cheia de fome dura 8 horas do mundo, para forçar 3 refeições por dia.
const HUNGER_WORLD_HOURS_TO_EMPTY = 8;
const THIRST_TICK_INTERVAL_MS = 60 * 1000;
const THIRST_WORLD_HOURS_TO_EMPTY = 4;

function clamp(n, min, max) {
  return Math.max(min, Math.min(max, n));
}

function toFiniteNumber(value, fallback = 0) {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

module.exports = {
  DT_MAX,
  MOVE_STAMINA_DRAIN_PER_SEC,
  MOVE_STAMINA_DRAIN_WARN_RATIO,
  MOVE_STAMINA_DRAIN_DANGER_RATIO,
  MOVE_STAMINA_DRAIN_WARN_MULTIPLIER,
  MOVE_STAMINA_DRAIN_DANGER_MULTIPLIER,
  STAMINA_BASE_REGEN_PER_SEC,
  HP_BASE_REGEN_PER_SEC,
  MOVE_SPEED_AT_ZERO_STAMINA_MULTIPLIER,
  DEFAULT_TERRAIN_DRAIN_MULTIPLIER,
  DEFAULT_STAMINA_REGEN_MULTIPLIER,
  DEFAULT_HP_REGEN_MULTIPLIER,
  DEFAULT_HUNGER_ITEM_RECOVERY,
  HUNGER_TICK_INTERVAL_MS,
  HUNGER_WORLD_HOURS_TO_EMPTY,
  THIRST_TICK_INTERVAL_MS,
  THIRST_WORLD_HOURS_TO_EMPTY,
  clamp,
  toFiniteNumber,
};
