// server/config/combatConstants.js

const COMBAT_BASE_COOLDOWN_MS = 5000;
const MELEE_ATTACK_STAMINA_COST = 5;
const RANGED_ATTACK_STAMINA_COST = 3;
const RANGED_ATTACK_MIN_RANGE = 2;

module.exports = {
  COMBAT_BASE_COOLDOWN_MS,
  MELEE_ATTACK_STAMINA_COST,
  RANGED_ATTACK_STAMINA_COST,
  RANGED_ATTACK_MIN_RANGE,
};
