// server/config/interactionConstants.js

const DEFAULT_STOP_RADIUS = 1.25;
const DEFAULT_TIMEOUT_MS = 8000;
const DEFAULT_COLLECT_RADIUS = 1.6;
const DEFAULT_COLLECT_COOLDOWN_MS = 4000;

module.exports = {
  DEFAULT_STOP_RADIUS,
  DEFAULT_TIMEOUT_MS,
  DEFAULT_COLLECT_RADIUS,
  DEFAULT_COLLECT_COOLDOWN_MS,
};
