// server/config/movementConstants.js

const CLICK_MOVE_SPAM_MS = 100;
const MOVE_STAMINA_DRAIN_PER_SEC = 1;
const MOVE_STAMINA_DRAIN_WARN_RATIO = 0.75;
const MOVE_STAMINA_DRAIN_DANGER_RATIO = 0.95;
const MOVE_STAMINA_DRAIN_WARN_MULTIPLIER = 1.3;
const MOVE_STAMINA_DRAIN_DANGER_MULTIPLIER = 2;
const STAMINA_BASE_REGEN_PER_SEC = 0.1;
const HP_BASE_REGEN_PER_SEC = 0.1;
const MOVE_SPEED_AT_ZERO_STAMINA_MULTIPLIER = 0.5;

module.exports = {
  CLICK_MOVE_SPAM_MS,
  MOVE_STAMINA_DRAIN_PER_SEC,
  MOVE_STAMINA_DRAIN_WARN_RATIO,
  MOVE_STAMINA_DRAIN_DANGER_RATIO,
  MOVE_STAMINA_DRAIN_WARN_MULTIPLIER,
  MOVE_STAMINA_DRAIN_DANGER_MULTIPLIER,
  STAMINA_BASE_REGEN_PER_SEC,
  HP_BASE_REGEN_PER_SEC,
  MOVE_SPEED_AT_ZERO_STAMINA_MULTIPLIER,
};
