// server/config/movementConstants.js

const CLICK_MOVE_SPAM_MS = 100;
const MOVE_STAMINA_DRAIN_PER_SEC = 1;
const MOVE_STAMINA_DRAIN_WARN_RATIO = 0.75;
const MOVE_STAMINA_DRAIN_DANGER_RATIO = 0.95;
const MOVE_STAMINA_DRAIN_WARN_MULTIPLIER = 1.3;
const MOVE_STAMINA_DRAIN_DANGER_MULTIPLIER = 2;

module.exports = {
  CLICK_MOVE_SPAM_MS,
  MOVE_STAMINA_DRAIN_PER_SEC,
  MOVE_STAMINA_DRAIN_WARN_RATIO,
  MOVE_STAMINA_DRAIN_DANGER_RATIO,
  MOVE_STAMINA_DRAIN_WARN_MULTIPLIER,
  MOVE_STAMINA_DRAIN_DANGER_MULTIPLIER,
};
