// server/state/spawn/spawnConfig.js

const SPAWN_TICK_MS = 1000;
const DEFAULT_SPAWN_SHAPE_KIND = "POINT";
const DEFAULT_SPAWN_RADIUS = 1;
const DEFAULT_SPAWN_MAX_ALIVE = 1;
const DEFAULT_SPAWN_QUANTITY_MIN = 1;
const DEFAULT_SPAWN_QUANTITY_MAX = 1;
const DEFAULT_INSTANCE_ENEMY_SPAWN_ENABLED = true;
const DEFAULT_INSTANCE_RESPAWN_MULTIPLIER = 1;
const DEFAULT_INSTANCE_SPAWN_QUANTITY_MULTIPLIER = 1;
const DEFAULT_INSTANCE_MAX_ALIVE_MULTIPLIER = 1;

module.exports = {
  SPAWN_TICK_MS,
  DEFAULT_SPAWN_SHAPE_KIND,
  DEFAULT_SPAWN_RADIUS,
  DEFAULT_SPAWN_MAX_ALIVE,
  DEFAULT_SPAWN_QUANTITY_MIN,
  DEFAULT_SPAWN_QUANTITY_MAX,
  DEFAULT_INSTANCE_ENEMY_SPAWN_ENABLED,
  DEFAULT_INSTANCE_RESPAWN_MULTIPLIER,
  DEFAULT_INSTANCE_SPAWN_QUANTITY_MULTIPLIER,
  DEFAULT_INSTANCE_MAX_ALIVE_MULTIPLIER,
};
