// server/state/spawn/spawnConfig.js

const SPAWN_TICK_MS = 180000; // 3 minutos (180 segundos)
const DEFAULT_SPAWN_SHAPE_KIND = "POINT";
const DEFAULT_SPAWN_RADIUS = 1;
const DEFAULT_SPAWN_MAX_ALIVE = 1;
const DEFAULT_SPAWN_QUANTITY_MIN = 1;
const DEFAULT_SPAWN_QUANTITY_MAX = 1;

module.exports = {
  SPAWN_TICK_MS,
  DEFAULT_SPAWN_SHAPE_KIND,
  DEFAULT_SPAWN_RADIUS,
  DEFAULT_SPAWN_MAX_ALIVE,
  DEFAULT_SPAWN_QUANTITY_MIN,
  DEFAULT_SPAWN_QUANTITY_MAX,
};
